#!/usr/bin/env python3
"""
fill_paper_numbers.py

Auto-fills the red \\pending{...} numbers in icbinb_prism.tex from the result
CSVs produced by the extension pipeline, so no number is ever typed by hand.

It reads:
  <stress_dir>/A_collapse_profile.csv      (per-model repetition-collapse rate)
  <stress_dir>/B_artifact_isolation.csv    (per-model substitution inflation)
and writes:
  paper_numbers.tex                         (\\renewcommand definitions)

icbinb_prism.tex does \\IfFileExists{paper_numbers.tex}{\\input{...}}{}, so:
  * before you run the notebook -> paper_numbers.tex is absent -> the paper
    shows red "[pending: <source>]" markers (nothing is fabricated);
  * after you run it and run this script -> the macros are overridden with the
    REAL values and the reds disappear on the next LaTeX build.

USAGE
-----
python fill_paper_numbers.py \
    --stress_dir /content/drive/MyDrive/PRISM/genmodel_bias/results/stress_test \
    --out paper_numbers.tex
"""

import argparse
import os
import shutil

import pandas as pd


def copy_figure(src, dst):
    if src and os.path.isfile(src):
        shutil.copyfile(src, dst)
        print(f"[fill] figure {os.path.basename(src)} -> {dst}")
        return True
    print(f"[fill] figure not found ({src}); paper keeps its placeholder box.")
    return False


def collapse_rate(a_csv, model):
    df = pd.read_csv(a_csv)
    sub = df[df["model"] == model]
    if sub.empty:
        return None
    return 100.0 * float(sub["collapse_rate"].mean())


def inflation_factor(b_csv, model):
    """Median over genes of (kept,strict) / (filtered,permissive) total
    substitution counts -- identical to stress_test's _summarize_artifact."""
    df = pd.read_csv(b_csv)
    sub = df[df["model"] == model]
    ratios = []
    for gene, g in sub.groupby("gene"):
        worst = g[(g["degenerate"] == "kept") & (g["aligner"] == "strict")]
        best = g[(g["degenerate"] == "filtered") & (g["aligner"] == "permissive")]
        if len(worst) and len(best) and float(best["total_substitutions"].iloc[0]) > 0:
            ratios.append(float(worst["total_substitutions"].iloc[0])
                          / float(best["total_substitutions"].iloc[0]))
    if not ratios:
        return None
    return float(pd.Series(ratios).median())


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--stress_dir", required=True,
                    help="Directory with A_collapse_profile.csv, B_artifact_isolation.csv, "
                         "and A_collapse.png.")
    ap.add_argument("--sweep_dir", default=None,
                    help="Directory with sweep_robustness.png (from sweep_decoding.py analyze).")
    ap.add_argument("--paper_dir", default=".",
                    help="Directory holding icbinb_prism.tex (where figures are copied).")
    ap.add_argument("--out", default="paper_numbers.tex")
    args = ap.parse_args(argv)

    a_csv = os.path.join(args.stress_dir, "A_collapse_profile.csv")
    b_csv = os.path.join(args.stress_dir, "B_artifact_isolation.csv")
    for f in (a_csv, b_csv):
        if not os.path.isfile(f):
            raise SystemExit(f"[fill] missing {f} -- run stress_test_generation.py first.")

    lines = ["% AUTO-GENERATED by fill_paper_numbers.py -- do not edit by hand.",
             "% Overrides the \\pending{...} defaults in icbinb_prism.tex with real values."]
    macros = {
        "EvoCollapse":        (collapse_rate(a_csv, "evo2"),      "{:.1f}\\%"),
        "CarbonInflation":    (inflation_factor(b_csv, "carbon"),    "{:.1f}"),
        "GeneratorInflation": (inflation_factor(b_csv, "generator"), "{:.1f}"),
        "EvoInflation":       (inflation_factor(b_csv, "evo2"),      "{:.2f}"),
    }
    for name, (val, fmt) in macros.items():
        if val is None:
            print(f"[fill] WARNING: could not compute {name} (model row absent) -- "
                  f"leaving it pending.")
            continue
        lines.append(f"\\renewcommand{{\\{name}}}{{{fmt.format(val)}}}")
        print(f"[fill] {name} = {fmt.format(val)}")

    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[fill] wrote {args.out}.")

    # Copy the two figures into the paper directory under the names the .tex expects.
    copy_figure(os.path.join(args.stress_dir, "A_collapse.png"),
                os.path.join(args.paper_dir, "fig_collapse.png"))
    if args.sweep_dir:
        copy_figure(os.path.join(args.sweep_dir, "sweep_robustness.png"),
                    os.path.join(args.paper_dir, "fig_sweep.png"))
    print("[fill] Rebuild icbinb_prism.tex to populate the reds and figures.")


if __name__ == "__main__":
    main()
