#!/usr/bin/env python3
"""
fill_structural.py

Auto-fills the SIMBIOCHEM paper's structural-drift numbers from
structural_drift_summary.csv (produced by structural_drift.py's ESMFold pilot),
so no structural number is typed by hand. Mirrors fill_paper_numbers.py for the
ICBINB paper.

Writes struct_numbers.tex with \\renewcommand overrides for:
  \\StructMaxDpLDDT      largest mean foldability drop (most negative mean ΔpLDDT)
  \\StructMaxDpLDDTSig   the signature achieving it
  \\StructMaxRMSD        largest mean CA-RMSD across signatures
  \\StructTruncRange     min–max truncation rate across signatures

simbiochem_prism.tex does \\IfFileExists{struct_numbers.tex}{\\input}{}, so the
paper shows red [pending: ESMFold pilot] markers until this runs, then the reals.

USAGE
-----
python fill_structural.py \
    --summary results/structural_drift/structural_drift_summary.csv \
    --out papers/struct_numbers.tex
"""
import argparse
import os

import pandas as pd


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--summary", required=True,
                    help="structural_drift_summary.csv from structural_drift.py")
    ap.add_argument("--out", default="papers/struct_numbers.tex")
    args = ap.parse_args(argv)

    if not os.path.isfile(args.summary):
        raise SystemExit(f"[fill_struct] missing {args.summary} -- run structural_drift.py (§8) first.")
    df = pd.read_csv(args.summary)

    # aggregate mean over genes, per signature (folded rows only)
    dp = df.dropna(subset=["mean_delta_plddt"])
    rm = df.dropna(subset=["mean_ca_rmsd"])
    lines = ["% AUTO-GENERATED by fill_structural.py -- do not edit by hand."]

    if len(dp):
        by = dp.groupby("signature")["mean_delta_plddt"].mean()
        sig = by.idxmin()  # largest foldability DROP = most negative
        lines.append(f"\\renewcommand{{\\StructMaxDpLDDT}}{{{by.min():+.1f}}}")
        lines.append(f"\\renewcommand{{\\StructMaxDpLDDTSig}}{{{sig}}}")
        print(f"[fill_struct] max ΔpLDDT drop = {by.min():+.1f} ({sig})")
    else:
        print("[fill_struct] WARNING: no folded ΔpLDDT rows (ESMFold produced nothing) "
              "-- leaving ΔpLDDT pending; truncation still available.")

    if len(rm):
        by = rm.groupby("signature")["mean_ca_rmsd"].mean()
        lines.append(f"\\renewcommand{{\\StructMaxRMSD}}{{{by.max():.2f}}}")
        print(f"[fill_struct] max CA-RMSD = {by.max():.2f} A")

    if "truncation_rate" in df:
        tr = df.groupby("signature")["truncation_rate"].mean()
        lo, hi = tr.min(), tr.max()
        lines.append(f"\\renewcommand{{\\StructTruncRange}}{{{lo:.0%}--{hi:.0%}}}"
                     .replace("%", "\\%"))
        print(f"[fill_struct] truncation range = {lo:.0%}-{hi:.0%}")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[fill_struct] wrote {args.out}. Also copy results/structural_drift/structural_drift.png "
          f"next to the .tex for Figure. Rebuild simbiochem_prism.tex.")


if __name__ == "__main__":
    main()
